"""adds one selected column

Revision ID: 5e8c2d180cc8
Revises: d3cd7b34bc21
Create Date: 2023-02-07 10:23:12.242430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8c2d180cc8'
down_revision = 'd3cd7b34bc21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'selected')
    # ### end Alembic commands ###
