"""empty message

Revision ID: d3cd7b34bc21
Revises: 25d5a333f647
Create Date: 2023-02-06 13:42:00.225034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cd7b34bc21'
down_revision = '25d5a333f647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('card', 'display_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('display_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('card', 'status')
    # ### end Alembic commands ###
